# Agenda PN26

La agenda de la Plataforma Nacional se diseñó para articular espacios de diálogo, aprendizaje y toma de decisiones estratégicas, incluyendo sesiones plenarias, paneles temáticos y presentaciones de alto nivel. La agenda se concertó con anfitriones y coanfitriones del nivel territorial, sectorial, cooperantes internacionales, academia y/o sociedad civil con el propósito de brindar oportunidades amplias y diversas de participación para todas las partes interesadas asistentes y sus distintos ámbitos de acción e interés.

Así mismo, en el marco del evento se desarrollarán otras actividades complementarias como laboratorios de innovación, talleres especializados, reuniones de alto nivel y encuentros técnicos, que permitieron profundizar en los enfoques y ejes transversales de la Plataforma Nacional que permitieron fomentar la colaboración multisectorial y generar insumos prácticos para la gestión del riesgo de desastres y la resiliencia territorial.

La agenda de contó con los siguientes espacios:

-   **Ceremonia de apertura**: inicio formal del evento en formato plenaria con la participación de todos los asistentes.

-   **Sesiones plenarias y paneles de discusión**: sesiones principales conducidas por expertos y/o expertas nacionales y/o internacionales. Abordan los temas más importantes de la Plataforma Nacional.

-   **Sesiones paralelas y/o temáticas**: bloques de tiempo para desarrollar varias temáticas específicas, relacionadas con los enfoques de la Plataforma Nacional. Las sesiones se desarrollan siguiendo metodologías como charlas cortas, paneles o dinámicas grupales. ●

-   **Laboratorios de aprendizaje**: fueron espacios para experimentar, intercambiar conocimientos, compartir metodologías, y co-crear soluciones para fortalecer la gestión del riesgo de desastres.

-   **Espacios en vivo**: fueron conferencias de formato corto, conciso y rápido (15 minutos) que se programaron en un espacio abierto para que los expositores presenten de manera atractiva y didáctica sus experiencias innovadoras y significativas, el nuevo conocimiento, las nuevas tecnologías, o los resultados de sus proyectos. La selección de expositores se realizó mediante convocatoria pública y previo concurso, a través de un proceso transparente de evaluación y selección llevado a cabo por un jurado calificador designado para tal efecto.

-   **Stands institucionales**: fueron espacios físicos destinados a exhibir, divulgar, visibilizar, comunicar, informar los resultados, avances, programas, proyectos, herramientas, o la misión institucional de los actores del SNGRD. Los stands contaron con unas dimensiones, especificaciones. Los costos asociados al montaje de cada stand serán responsabilidad de cada institución.

-   **Ceremonia de clausura**: al finalizar el evento existió un espacio para presentar el manifiesto oficial de la Plataforma Nacional, elaborado por los diferentes integrantes del SNGRD, así como para realizar anuncios de relevancia y cierres de gestión.

<iframe src="Agenda-PN26-v4.pdf" width="100%" height="900" style="border: none;"></iframe>
