## Sesiones paralelas

1. [Colombia ante las Amenazas Extraterrestres: Ciencia, Riesgo y Política Pública](sp-01/index.qmd)
2. [Avances en el sistema de alertas por ciclones tropicales: evolución operativa e innovación](sp-02/index.qmd)
3. [Protegiendo e impulsando el desarrollo a nivel territorial a través de la continuidad de las operaciones en las cadenas de suministro a nivel nacional frente a los efectos del cambio climático y los desastres](sp-04/index.qmd)
4. [Educación en gestión del riesgo a lo largo de la vida](sp-05/index.qmd)
5. [Escuelas resilientes: Un análisis en la política de gestión integral del riesgo y educación en emergencias desde la iniciativa del consorcio Creer en Arauca y Tumaco](sp-06/index.qmd)
6. [¿Por qué y en dónde ocurren las avenidas torrenciales? Priorización de cuencas para estudios básicos de amenaza por avenidas torrenciales](sp-07/index.qmd)
7. [Hospitales Resilientes Frente a Emergencias de Salud y Desastres](sp-08/index.qmd)
8. [Alianzas que transforman la Gestión del Riesgo de Desastres](sp-09/index.qmd)
9. [¿Por qué se apagan los radares? El reto de mantener vivos los ojos del país frente a las lluvias y eventos extremos](sp-10/index.qmd)
10. [Reducir el Riesgo y Salvaguardar la Biodiversidad: Estrategias Integradas de Resiliencia](sp-11/index.qmd)
11. [Camino hacia Tsunami Ready en Colombia: Capacidades, desafíos y articulación institucional](sp-12/index.qmd)
12. [Anticipar, planificar y resistir: los desafíos de la gestión del riesgo de desastres](sp-13/index.qmd)
13. [Gestión del riesgo en el sector agropecuario: desarrollo rural, financiamiento e innovación para la resiliencia de los territorios rurales](sp-14/index.qmd)
14. [Towards 'Caribbean Sea Resilience Framework Initiative' through advancing investment in Disaster Risk Reduction](sp-15/index.qmd)
15. [Riesgo NATECH en Colombia: gobernanza público-privada para la reducción de riesgos complejos y sistémicos](sp-16/index.qmd)
16. [De la observación a la acción: CopernicusLAC en la gestión del riesgo multiamenazas en Colombia](sp-17/index.qmd)
17. [Implementación de la Política Pública de GRD en las IES Colombianas (Fase diagnóstica)](sp-18/index.qmd)
18. [Animales y desastres, una mirada desde la sociedad civil para fortalecer la resiliencia de los territorios](sp-19/index.qmd)
19. [Áreas Protegidas y gestión del riesgo climático: el rol estratégico del SINAP y de las autoridades ambientales en la construcción de territorios resilientes](sp-20/index.qmd)
20. [Semillas de resiliencia: el aula como espacio de conocimiento del riesgo](sp-21/index.qmd)
21. [Del dato a la decisión: IA para la gestión del riesgo](sp-22/index.qmd)
22. [El Ejército Colombiano, pilar fundamental de la Gestión del Riesgo](sp-23/index.qmd)
23. [De la naturaleza al territorio: validación técnica de la Adaptación Basada en Ecosistemas (AbE) para su integración en la gestión del riesgo climático](sp-24/index.qmd)
24. [Género, datos e innovación: Del compromiso global a la acción territorial](sp-25/index.qmd)
25. [Cuando los datos se vuelven protección: Visión geoespacial para la transferencia del riesgo](sp-27/index.qmd)
26. [Invertir en prevención: responsabilidad fiscal y sostenibilidad en la gestión del riesgo de desastres](sp-28/index.qmd)
27. [¿Quién paga el riesgo? Financiamiento de la resiliencia en contextos de alta exposición a desastres](sp-29/index.qmd)
28. [El colapso climático y ambiental en Colombia: Diagnóstico para una resiliencia territorial sostenible](sp-30/index.qmd)
29. [Supervisión Basada en Riesgos con un enfoque en la resiliencia de los servicios públicos domiciliarios](sp-31/index.qmd)
30. [Hacia territorios resilientes en Colombia: orientaciones conceptuales para política e inversión pública](sp-32/index.qmd)
31. [Respuesta Humanitaria Inclusiva: Una apuesta centrada en las mujeres y personas con discapacidad](sp-33/index.qmd)
32. [Construyendo Espacios de Paz en la Ruralidad](sp-34/index.qmd)
33. [Sistemas Alimentarios Resilientes: Estrategias de Adaptación frente al Riesgo Climático en Colombia](sp-35/index.qmd)
34. [Preparación ante emergencias y movilidad humana](sp-37/index.qmd)
35. [Puentes con la Gente y para la Gente](sp-38/index.qmd)
